name: build-and-push-docker
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Sanity-Check
      - name: Verify Docker Hub login
        run: |
          set -e
          echo "Token length: $(echo '${{ secrets.DOCKERHUB_TOKEN }}' | wc -c)"
          docker login docker.io -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin <<< "${{ secrets.DOCKERHUB_TOKEN }}"
          docker whoami || true
          docker pull docker.io/library/hello-world:latest

      - name: Build and push (latest)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: zakibnf/shop-frontend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
